### ISSUE TITLE
respeaker_ros: No definition of [audio_common_msgs] for OS version [stretch]

### ISSUE THREAD

**Issue by auvilink** [furushchev/respeaker_ros#1]
Trying to install this on Raspberry Pi stretch (ROS installed) with 

rosdep install --from-paths src -i -r -n -y

got this error:

respeaker_ros: No definition of [audio_common_msgs] for OS version [stretch]

Any help please.

thanks.

**Comment by furushchev** [comment]
It looks the package is not yet released on your OS or distribution. 
In that case, you can still manually install the package from source. 
Please try the commands as followings:

```
cd path/to/catkin/workspace
wstool set -t src ros-drivers/audio_common --git https://github.com/ros-drivers/audio_common -u -y
rosdep install --from-paths src -i -r -n -y
catkin build respeaker_ros
```

**Comment by auvilink** [comment]
Thanks, I figured that out and installed the package.
