### ISSUE TITLE
Could not find a package configuration file provided

### ISSUE THREAD

**Issue by Wzom** [furushchev/respeaker_ros#14]
Trying to install this on Raspberry Pi stretch (ROS installed) with
catkin build respeaker_ros

got this error:

Could not find a package configuration file provided by "catkin_virtualenv" 
with any of the following names:
    catkin_virtualenvConfig.cmake
    catkin_virtualenv-config.cmake

Any help please.

thanks.

**Comment by furushchev** [comment]
It looks you did not install `catkin_virtualenv` which is one of dependency.
Did you run `rosdep install`?

FYI, Please don't double post to this issue and my personal e-mail.

Thanks.

**Comment by Wzom** [comment]
Thank you, I have installed the dependency now. The problem has been solved

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Yuki Furuta <notifications@github.com>
发送时间: Saturday, May 11, 2019 5:58:43 PM
收件人: furushchev/respeaker_ros
抄送: Wzom; Author
主题: Re: [furushchev/respeaker_ros] Could not find a package configuration file provided (#14)


It looks you did not install catkin_virtualenv which is one of dependency.
Did you run rosdep install?

FYI, Please don't double post to this issue and my personal e-mail.

Thanks.

―

**Comment by furushchev** [comment]
Good to hear that your issue was now solved.
