### ISSUE TITLE
ValueError: Invalid audio channels

### ISSUE THREAD

**Issue by feifeiwei** [furushchev/respeaker_ros#17]
hey
thanks for your nice work, but recently i have got a knotty problem when a run [roslaunch respeaker_ros respeaker.launch]. output log is shown below. could you give me some advices?Thank you in advance.
your sincerely
---------------------------------------------------------------------------------------------------------------------

[INFO] [1567732215.569230]: Found 8: ReSpeaker 4 Mic Array (UAC1.0): USB Audio (hw:3,0) (channels: 0)
[WARN] [1567732215.569561]: 0 channel is found for respeaker
[WARN] [1567732215.569809]: You may have to update firmware.
Traceback (most recent call last):
  File "/home/xbot/mengfei_ws/src/respeaker_ros/scripts/respeaker_node.py", line 428, in <module>
    n = RespeakerNode()
  File "/home/xbot/mengfei_ws/src/respeaker_ros/scripts/respeaker_node.py", line 323, in __init__
    self.respeaker_audio = RespeakerAudio(self.on_audio, suppress_error=suppress_pyaudio_error)
  File "/home/xbot/mengfei_ws/src/respeaker_ros/scripts/respeaker_node.py", line 259, in __init__
    input_device_index=self.device_index,
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
ValueError: Invalid audio channels
Exception AttributeError: "'RespeakerAudio' object has no attribute 'stream'" in <bound method RespeakerAudio.__del__ of <__main__.RespeakerAudio object at 0x7f6594adf410>> ignored
[respeaker_node-1] process has died [pid 6879, exit code 1, cmd /home/xbot/mengfei_ws/devel/lib/respeaker_ros/respeaker_node.py __name:=respeaker_node __log:=/home/xbot/.ros/log/18620894-d041-11e9-a3b9-2b9a926590f0/respeaker_node-1.log].
log file: /home/xbot/.ros/log/18620894-d041-11e9-a3b9-2b9a926590f0/respeaker_node-1*.log

**Comment by sasha177** [comment]
Hi, how did you resolve this?
