### ISSUE TITLE
Any chance to support 4MICs HAT for Raspberry Pi

### ISSUE THREAD

**Issue by auvilink** [furushchev/respeaker_ros#2]
I have ROS installed on Raspberry Pi with 4MICs array. (4MICs HAT for Raspberry Pi)

Any chance this would support that hardware? 

Thanks.

**Comment by furushchev** [comment]
Hi,

I only have respeaker v2.0 and can only check if it works or not. Sorry.

**Comment by auvilink** [comment]
I tried and it got stuck on 
roslaunch respeaker_ros respeaker.launch

Traceback (most recent call last):
  File "/home/pi/catkin_ws/src/respeaker_ros/scripts/respeaker_node.py", line 344, in <module>
    n = RespeakerNode()
  File "/home/pi/catkin_ws/src/respeaker_ros/scripts/respeaker_node.py", line 264, in __init__
    self.respeaker = RespeakerInterface()
  File "/home/pi/catkin_ws/src/respeaker_ros/scripts/respeaker_node.py", line 84, in __init__
    raise RuntimeError("Failed to find Respeaker device")
RuntimeError: ## Failed to find Respeaker device

It's totally reasonable going this far considering I used a different mic array.

Maybe if I can get this line working then it would work.

self.dev = usb.core.find(idVendor=self.VENDOR_ID,
                                 idProduct=self.PRODUCT_ID)

Thanks.

**Comment by auvilink** [comment]
I purchased the new ReSpeaker Mic Array v2.0 to save the hassle.
Thanks.
