### ISSUE TITLE
No module named sound_play.msg

### ISSUE THREAD

**Issue by iPwnXX** [furushchev/respeaker_ros#21]
Having issue after launching  "roslaunch respeaker_ros respeaker.launch"
![issue](https://user-images.githubusercontent.com/40853420/115952061-a4f03000-a516-11eb-99df-d61c175dbeb4.png)

happened in speech_to_text.py: from sound_play.msg import

I installed all required package listed in requirement.txt, and have no problem of other respeaker functions except this one

**Comment by furushchev** [comment]
It looks dependencies of the packagge is missing.
Please check if you forgot any commands described below (especially `rosdep`) :
https://github.com/furushchev/respeaker_ros#readme

**Comment by iPwnXX** [comment]
` rosdep install sound_play  
rosmake sound_play`
not listed in readme.
