### ISSUE TITLE
Sound source distance

### ISSUE THREAD

**Issue by auvilink** [furushchev/respeaker_ros#3]
rostopic echo /speech_localization # Result of DoA as Pose

Does this mean it can give out the sound source distance? (not only sound direction of arrival, but the actual distance).

Thanks a lot.

**Comment by furushchev** [comment]
No, it returns only a direction of arrival. (the type of this topic is `geometry_msgs/PoseStamped` but only quaternion is filled.)
Sorry for confusing.

**Comment by auvilink** [comment]
ok, thanks.
