### ISSUE TITLE
roslaunch Access denied (insufficient permissions

### ISSUE THREAD

**Issue by auvilink** [furushchev/respeaker_ros#4]
This is the new ReSpeaker Mic Array v2.0 with raspberry pi (raspbian stretch + ROS Kinetic).

Everything works fine until

roslaunch respeaker_ros respeaker.launch

File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

Any ideas?

Thank you so much.

**Comment by furushchev** [comment]
@auvilink Good catch! I added a setting file for giving the right permission to the device and updated the README. Please try again!
